import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "id" | "zh";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
};

// Translation keys
const translations = {
    id: {
        email: "E-Mail",
        password: "Kata Sandi",
        login: "Masuk",
        logout: "Keluar",
        forgotPassword: "Lupa Kata Sandi?",
        home: "Beranda",
        recruitment: "Rekrutmen",
        sales: "Sales",
        employee: "Karyawan",
        profile: "Profil",
        resume: "Resume",
        approve: "Setujui",
        reject: "Tolak",
        experiences: "Pengalaman",
        expectedSalary: "Gaji yang Diharapkan",
        interviewScores: "Skor Interview",
        contactInformation: "Informasi Kontak",
        genderAndAge: "Jenis Kelamin, Usia",
        yearsOld: "tahun",
        dateOfBirth: "Tanggal Lahir",
        phoneNumber: "Nomor Telepon",
        identityCardAddress: "Alamat KTP",
        domisileAddress: "Alamat Domisili",
        ProfessionalInformation: "Informasi Profesional",
        educations: "Pendidikan",
        noEducationsAvailable: "Tidak ada informasi pendidikan",
        workExperiences: "Pengalaman Kerja",
        noWorkExperiencesAvailable: "Tidak ada pengalaman kerja",
        organizations: "Organisasi",
        noOrganizationsAvailable: "Tidak ada organisasi",
        certificates: "Sertifikat",
        noCertificatesAvailable: "Tidak ada sertifikat",
        skills: "Keahlian",
        noSkillsAvailable: "Tidak ada keahlian",
        languages: "Bahasa",
        noLanguagesAvailable: "Tidak ada bahasa",
        recruitmentReviews: "Ulasan HRD",
        abilityScores: "Nilai Kemampuan",
        interviewNotes: "Catatan Interview",
        approvedBy: "Disetujui oleh",
        at: "pada",
        position: "Posisi",
        allPositions: "Semua Posisi",
        clearAll: "Bersihkan Semua",
        candidates: "Kandidat",
        candidateList: "Daftar Kandidat",
        confirm_approveCandidate: "Yakin ingin menyetujui kandidat?",
        confirm_rejectCandidate: "Yakin ingin menolak kandidat?",
        salaries: "Penawaran Gaji",
        salaryList: "Daftar Penawaran Gaji",
        confirm_approveSalary: "Yakin ingin menyetujui penawaran gaji?",
        confirm_rejectSalary: "Yakin ingin menolak penawaran gaji?",
        dailyQuotes: "Penawaran Harian",
        pointOfSales: "Titik Penjualan",
        salesIns: "Penjualan Masuk",
        salesInReports: "Laporan Penjualan",
        recapDailyQuotes: "Rekap Penawaran Harian",
        salesList: "Daftar Penjualan",
        allSales: "Semua Sales",
        supervisor: "Supervisor",
        allSupervisors: "Semua Supervisor",
        manager: "Manajer",
        allManagers: "Semua Manajer",
        newCustomers: "Pelanggan Baru",
        existingCustomers: "Pelanggan Lama",
        totalQuotations: "Total Penawaran",
        newAmount: "Total Baru",
        existingAmount: "Total Lama",
        grandTotal: "Total Keseluruhan",
        record: "Catatan",
        records: "Catatan",
        quotes: "penawaran",
        million: "Jt",
        jan: "Jan",
        feb: "Feb",
        mar: "Mar",
        apr: "Apr",
        may: "Mei",
        jun: "Jun",
        jul: "Jul",
        aug: "Agu",
        sep: "Sep",
        oct: "Okt",
        nov: "Nov",
        dec: "Des",
        ordersThisYear: "Order Tahun Ini",
        ordersToday: "Order Hari Ini",
        salesThisMonth: "Penjualan Bulan Ini",
        salesThisYear: "Penjualan Tahun Ini",
        sellingPerformanceThisYear: "Performa Penjualan Tahun Ini",
        listOfSalesIns: "Daftar Penjualan Masuk",
        paymentType: "Tipe Pembayaran",
        allPaymentTypes: "Semua Tipe Pembayaran",
        accountType: "Tipe Akun",
        allAccountTypes: "Semua Tipe Akun",
        todaysIncome: "Pendapatan Hari Ini",
        thisMonthsIncome: "Pendapatan Bulan Ini",
        thisYearsIncome: "Pendapatan Tahun Ini",
        completed: "Selesai",
        inProgress: "Sedang Berjalan",
        totalIncome: "Total Pendapatan",
        allEmployees: "Semua Karyawan",
        accessDoor: "Pintu Akses",
        gpsView: "GPS Kendaraan",
        employeeList: "Daftar Karyawan",
        employeeProfile: "Profil Karyawan",
        years: "tahun",
        months: "bulan",
        days: "hari",
        workPeriod: "Masa Kerja",
        employeeId: "ID Karyawan",
        contractRemaining: "Sisa Kontrak",
        personalInformation: "Informasi Pribadi",
        gender: "Jenis Kelamin",
        companyEmail: "Email Perusahaan",
        personalEmail: "Email Pribadi",
        nationalId: "NIK",
        address: "Alamat",
        maritalStatus: "Status Pernikahan",
        religion: "Agama",
        nationality: "Kebangsaan",
        employmentInformation: "Informasi Pekerjaan",
        department: "Departemen",
        grade: "Golongan",
        workStatus: "Status Kerja",
        startDate: "Tanggal Mulai",
        contractEndDate: "Tanggal Akhir Kontrak",
        professionalInformation: "Informasi Profesional",
        education: "Pendidikan",
        workExperience: "Pengalaman Kerja",
        accessLogList: "Riwayat Akses",
        granted: "Diizinkan",
        denied: "Ditolak",
        openAllDoors: "Buka Semua Pintu",
        normalizeAllDoors: "Normalkan Pintu",
        confirm_openAllDoors: "Yakin ingin membuka semua pintu?",
        confirm_normalizeAllDoors: "Yakin ingin menormalisasi semua pintu?",
        open: "Buka",
        normalize: "Normal",
        comingSoon: "Segera Hadir",
        featureIsCurrentlyBeingDeveloped: "Fitur sedang dikembangkan",
        vehicleGPSTracking: "Pelacakan GPS Kendaraan",
        connected: "Terhubung",
        disconnected: "Terputus",
        speed: "Kecepatan",
        Moving: "Berjalan",
        Idling: "Diam",
        Parking: "Parkir",
        offline: "Offline",
        unknown: "Tidak Diketahui",
        vehicleList: "Daftar Kendaraan",
        all: "Semua",
        motorcycle: "Motor",
        car: "Mobil",
        emailAddress: "Alamat Email",
        officeLocation: "Lokasi Kantor",
        accountSettings: "Pengaturan Akun",
        notifications: "Notifikasi",
        privacyAndSecurity: "Privasi & Keamanan",
        appPreferences: "Preferensi Aplikasi",
        support: "Bantuan",
        contactSupport: "Hubungi Bantuan",
        helpCenter: "Pusat Bantuan",
        welcome: "Selamat Datang",
        dashboard: "Dasbor",
        quickActions: "Aksi Cepat",
        recentActivities: "Aktivitas Terbaru",
        search: "Cari",
        noMoreData: "Tidak ada data lagi",
        noDataFound: "Data tidak ditemukan",
        filter: "Filter",
        today: "Hari Ini",
        thisWeek: "Minggu Ini",
        thisMonth: "Bulan Ini",
        total: "Total",
        amount: "Jumlah",
        status: "Status",
        date: "Tanggal",
        name: "Nama",
        active: "Aktif",
        inactive: "Tidak Aktif",
        loading: "Memuat...",
        editProfile: "Edit Profil",
        username: "Nama Pengguna",
        cancel: "Batal",
        saveChanges: "Simpan Perubahan",
        confirmLogout: "Yakin ingin keluar?",
        recommended: "Direkomendasikan",
        notRecommended: "Tidak direkomendasikan",
        holded: "Ditahan",
        other: "Lainnya",
        candidate: "Kandidat",
        hrd: "HRD",
        joined: "Bergabung",
        employees: "Karyawan",
        salaryOffers: "Penawaran Gaji",
        greeting_morning: "Selamat pagi",
        greeting_afternoon: "Selamat siang",
        greeting_evening: "Selamat sore",
        greeting_night: "Selamat malam",
        welcomeMessage: "Berikut overview perusahaan untuk hari ini",
        allStatuses: "Semua Status",
        fullName: "Nama Lengkap",
        normalizeDoors: "Normalkan Pintu",
        allDepartments: "Semua Departemen",
        employeeStatus: "Status Karyawan",
        device: "Perangkat",
        allDevices: "Semua Perangkat",
        category: "Kategori",
        allCategories: "Semua Kategori",
        changePassword: "Ubah Password",
        currentPassword: "Password Saat Ini",
        newPassword: "Password Baru",
        confirmNewPassword: "Konfirmasi Password Baru",
        credential: "Nama Pengguna / E-Mail",
        allMenus: "Semua Menu",
        accessDoors: "Akses Pintu",
        pageNotFound: "Halaman Tidak Ditemukan",
        pageNotFoundDesc: "Halaman yang kamu cari tidak tersedia atau telah dipindahkan",
        backToHome: "Kembali ke Beranda",
        recruitments: "Rekrutmen",
        miscellaneous: "Lainnya",
        welcomeBack: "Selamat Datang Kembali",
        forbidden: "Akses Ditolak",
        forbiddenDesc: "Anda tidak memiliki akses ke halaman ini",
        language: "Bahasa",
        english: "Bahasa Inggris",
        indonesian: "Bahasa Indonesia",
        chinese: "Bahasa Mandarin",
        theme: "Tema",
        light: "Terang",
        dark: "Gelap",
        system: "Sistem",
        close: "Tutup",
        menusList: "Daftar Menu",
    },

    en: {
        email: "E-Mail",
        password: "Password",
        login: "Login",
        logout: "Logout",
        forgotPassword: "Forgot Password?",
        home: "Home",
        recruitment: "Recruitment",
        sales: "Sales",
        employee: "Employee",
        profile: "Profile",
        resume: "Resume",
        approve: "Approve",
        reject: "Reject",
        experiences: "Experiences",
        expectedSalary: "Expected Salary",
        interviewScores: "Interview Scores",
        contactInformation: "Contact Information",
        genderAndAge: "Gender, Age",
        yearsOld: "years old",
        dateOfBirth: "Birth Date",
        phoneNumber: "Phone Number",
        identityCardAddress: "Identity Address",
        domisileAddress: "Domisile Address",
        ProfessionalInformation: "Professional Information",
        educations: "Educations",
        noEducationsAvailable: "No educations information available",
        workExperiences: "Work Experiences",
        noWorkExperiencesAvailable: "No work experiences information available",
        organizations: "Organizations",
        noOrganizationsAvailable: "No organizations information available",
        certificates: "Certificates",
        noCertificatesAvailable: "No certificates information available",
        skills: "Skills",
        noSkillsAvailable: "No skills information available",
        languages: "Languages",
        noLanguagesAvailable: "No languages information available",
        recruitmentReviews: "Recruitment Reviews",
        abilityScores: "Ability Scores",
        interviewNotes: "Interview Notes",
        approvedBy: "Approved by",
        at: "at",
        position: "Position",
        allPositions: "All Positions",
        clearAll: "Clear All",
        candidates: "Candidates",
        candidateList: "List of candidates",
        confirm_approveCandidate: "Are you sure want to approve candidate?",
        confirm_rejectCandidate: "Are you sure want to reject candidate?",
        salaries: "Salary Offers",
        salaryList: "List of salary offers",
        confirm_approveSalary: "Are you sure want to approve salary offers?",
        confirm_rejectSalary: "Are you sure want to reject salary offers?",
        dailyQuotes: "Daily Quotes",
        pointOfSales: "Point of Sales",
        salesIns: "Sales Ins",
        salesInReports: "Sales In Reports",
        recapDailyQuotes: "Recap Daily Quotes",
        salesList: "List of sales",
        allSales: "All Sales",
        supervisor: "Supervisor",
        allSupervisors: "All Supervisors",
        manager: "Manager",
        allManagers: "All Managers",
        newCustomers: "New Customers",
        existingCustomers: "Existing Customers",
        totalQuotations: "Total Quotations",
        newAmount: "New Amount",
        existingAmount: "Existing Amount",
        grandTotal: "Grand Total",
        record: "Record",
        records: "Records",
        quotes: "quotes",
        million: "M",
        jan: "Jan",
        feb: "Feb",
        mar: "Mar",
        apr: "Apr",
        may: "May",
        jun: "Jun",
        jul: "Jul",
        aug: "Aug",
        sep: "Sep",
        oct: "Oct",
        nov: "Nov",
        dec: "Dec",
        ordersThisYear: "Orders this year",
        ordersToday: "Orders today",
        salesThisMonth: "Sales this month",
        salesThisYear: "Sales this year",
        sellingPerformanceThisYear: "Selling performance this year",
        listOfSalesIns: "List of Sales Ins",
        paymentType: "Payment Type",
        allPaymentTypes: "All Payment Types",
        accountType: "Account Type",
        allAccountTypes: "All Account Types",
        todaysIncome: "Today's Income",
        thisMonthsIncome: "This Month's Income",
        thisYearsIncome: "This Year's Income",
        completed: "Completed",
        inProgress: "In Progress",
        totalIncome: "Total Income",
        allEmployees: "All Employees",
        accessDoor: "Access Door",
        gpsView: "GPS View",
        employeeList: "List of employees",
        employeeProfile: "Employee Profile",
        years: "years",
        months: "months",
        days: "days",
        workPeriod: "Work Period",
        employeeId: "Employee ID",
        contractRemaining: "Contract Remaining",
        personalInformation: "Personal Information",
        gender: "Gender",
        companyEmail: "Company E-Mail",
        personalEmail: "Personal E-Mail",
        nationalId: "National ID",
        address: "Address",
        maritalStatus: "Marital Status",
        religion: "Religion",
        nationality: "Nationality",
        employmentInformation: "Employment Information",
        department: "Department",
        grade: "Grade",
        workStatus: "Work Status",
        startDate: "Start Date",
        contractEndDate: "Contract End Date",
        professionalInformation: "Professional Information",
        education: "Education",
        workExperience: "Work Experience",
        accessLogList: "Recent Access Logs",
        granted: "Granted",
        denied: "Denied",
        openAllDoors: "Open All Doors",
        normalizeAllDoors: "Normalize All Doors",
        confirm_openAllDoors: "Are you sure want to open all doors?",
        confirm_normalizeAllDoors: "Are you sure want to normalize all doors?",
        open: "Open",
        normalize: "Normalize",
        comingSoon: "Coming Soon",
        featureIsCurrentlyBeingDeveloped: "Feature is currently being developed",
        vehicleGPSTracking: "Vehicle GPS Tracking",
        connected: "Connected",
        disconnected: "Disconnected",
        speed: "Speed",
        Moving: "Moving",
        Idling: "Idling",
        Parking: "Parking",
        offline: "Offline",
        unknown: "Unknown",
        vehicleList: "List of vehicles",
        all: "All",
        motorcycle: "Motorcycle",
        car: "Car",
        emailAddress: "Email Address",
        officeLocation: "Office Location",
        accountSettings: "Account Settings",
        notifications: "Notifications",
        privacyAndSecurity: "Privacy and Security",
        appPreferences: "App Preferences",
        support: "Support",
        contactSupport: "Contact Support",
        helpCenter: "Help Center",
        welcome: "Welcome",
        dashboard: "Dashboard",
        quickActions: "Quick Actions",
        recentActivities: "Recent Activities",
        search: "Search",
        noMoreData: "No more data available",
        noDataFound: "No data found",
        filter: "Filter",
        today: "Today",
        thisWeek: "This Week",
        thisMonth: "This Month",
        total: "Total",
        amount: "Amount",
        status: "Status",
        date: "Date",
        name: "Name",
        active: "Active",
        inactive: "Inactive",
        loading: "Loading...",
        editProfile: "Edit Profile",
        username: "Username",
        cancel: "Cancel",
        saveChanges: "Save Changes",
        confirmLogout: "Are you sure want to logout?",
        recommended: "Recommended",
        notRecommended: "Not Recommended",
        holded: "Holded",
        other: "Other",
        candidate: "Candidate",
        hrd: "HRD",
        joined: "Joined",
        employees: "Employees",
        salaryOffers: "Salary Offers",
        greeting_morning: "Good Morning",
        greeting_afternoon: "Good Afternoon",
        greeting_evening: "Good Evening",
        greeting_night: "Good Night",
        welcomeMessage: "Here's your company overview for today",
        allStatuses: "All Statuses",
        fullName: "Full Name",
        normalizeDoors: "Normalize Doors",
        allDepartments: "All Departments",
        employeeStatus: "Employee Status",
        device: "Device",
        allDevices: "All Devices",
        category: "Category",
        allCategories: "All Categories",
        changePassword: "Change Password",
        currentPassword: "Current Password",
        newPassword: "New Password",
        confirmNewPassword: "Confirm New Password",
        credential: "Username / E-Mail",
        allMenus: "All Menus",
        accessDoors: "Access Doors",
        pageNotFound: "Page Not Found",
        pageNotFoundDesc: "The page you are looking for is not available or has been moved",
        backToHome: "Back to Home",
        recruitments: "Recruitments",
        miscellaneous: "Misc",
        welcomeBack: "Welcome Back",
        forbidden: "Forbidden",
        forbiddenDesc: "The page you're trying to access has restricted access",
        language: "Language",
        english: "English",
        indonesian: "Indonesian",
        chinese: "Chinese",
        theme: "Theme",
        light: "Light",
        dark: "Dark",
        system: "System",
        close: "Close",
        menuList: "Menu List"
    },

    zh: {
        email: "电子邮件",
        password: "密码",
        login: "登录",
        logout: "登出",
        forgotPassword: "忘记密码？",
        home: "首页",
        recruitment: "招聘",
        sales: "销售",
        employee: "员工",
        profile: "个人资料",
        resume: "简历",
        approve: "批准",
        reject: "拒绝",
        experiences: "经验",
        expectedSalary: "期望薪资",
        interviewScores: "面试评分",
        contactInformation: "联系方式",
        genderAndAge: "性别，年龄",
        yearsOld: "岁",
        dateOfBirth: "出生日期",
        phoneNumber: "电话号码",
        identityCardAddress: "身份证地址",
        domisileAddress: "居住地址",
        ProfessionalInformation: "专业信息",
        educations: "教育背景",
        noEducationsAvailable: "暂无教育信息",
        workExperiences: "工作经历",
        noWorkExperiencesAvailable: "暂无工作经历",
        organizations: "组织",
        noOrganizationsAvailable: "暂无组织信息",
        certificates: "证书",
        noCertificatesAvailable: "暂无证书信息",
        skills: "技能",
        noSkillsAvailable: "暂无技能信息",
        languages: "语言",
        noLanguagesAvailable: "暂无语言信息",
        recruitmentReviews: "招聘评估",
        abilityScores: "能力评分",
        interviewNotes: "面试备注",
        approvedBy: "批准人",
        at: "于",
        position: "职位",
        allPositions: "所有职位",
        clearAll: "清除所有",
        candidates: "候选人",
        candidateList: "候选人名单",
        confirm_approveCandidate: "您确定要批准此候选人吗？",
        confirm_rejectCandidate: "您确定要拒绝此候选人吗？",
        salaries: "薪资提案",
        salaryList: "薪资列表",
        confirm_approveSalary: "您确定要批准此薪资提案吗？",
        confirm_rejectSalary: "您确定要拒绝此薪资提案吗？",
        dailyQuotes: "每日报价",
        pointOfSales: "销售点",
        salesIns: "销售入账",
        salesInReports: "销售入账报告",
        recapDailyQuotes: "每日报价汇总",
        salesList: "销售清单",
        allSales: "所有销售",
        supervisor: "主管",
        allSupervisors: "所有主管",
        manager: "经理",
        allManagers: "所有经理",
        newCustomers: "新客户",
        existingCustomers: "老客户",
        totalQuotations: "报价总数",
        newAmount: "新增金额",
        existingAmount: "已有金额",
        grandTotal: "总计",
        record: "记录",
        records: "记录",
        quotes: "报价",
        million: "百万",
        jan: "一月",
        feb: "二月",
        mar: "三月",
        apr: "四月",
        may: "五月",
        jun: "六月",
        jul: "七月",
        aug: "八月",
        sep: "九月",
        oct: "十月",
        nov: "十一月",
        dec: "十二月",
        ordersThisYear: "今年订单",
        ordersToday: "今日订单",
        salesThisMonth: "本月销售",
        salesThisYear: "今年销售",
        sellingPerformanceThisYear: "今年销售表现",
        listOfSalesIn: "销售入账清单",
        paymentType: "付款方式",
        allPaymentTypes: "所有付款方式",
        accountType: "账户类型",
        allAccountTypes: "所有账户类型",
        todaysIncome: "今日收入",
        thisMonthsIncome: "本月收入",
        thisYearsIncome: "今年收入",
        completed: "已完成",
        inProgress: "进行中",
        totalIncome: "总收入",
        allEmployees: "所有员工",
        accessDoor: "门禁",
        gpsView: "GPS视图",
        employeeList: "员工列表",
        employeeProfile: "员工资料",
        years: "年",
        months: "月",
        days: "天",
        workPeriod: "工作期限",
        employeeId: "员工编号",
        contractRemaining: "合同剩余时间",
        personalInformation: "个人信息",
        gender: "性别",
        companyEmail: "公司邮箱",
        personalEmail: "个人邮箱",
        nationalId: "身份证号",
        address: "地址",
        maritalStatus: "婚姻状况",
        religion: "宗教",
        nationality: "国籍",
        employmentInformation: "雇佣信息",
        department: "部门",
        grade: "等级",
        workStatus: "工作状态",
        startDate: "开始日期",
        contractEndDate: "合同结束日期",
        professionalInformation: "专业信息",
        education: "教育",
        workExperience: "工作经验",
        accessLogList: "最近访问记录",
        granted: "已授权",
        denied: "已拒绝",
        openAllDoors: "打开所有门",
        normalizeAllDoors: "恢复所有门状态",
        confirm_openAllDoors: "您确定要打开所有门吗？",
        confirm_normalizeAllDoors: "您确定要恢复所有门状态吗？",
        open: "打开",
        normalize: "恢复",
        comingSoon: "即将推出",
        featureIsCurrentlyBeingDeveloped: "该功能正在开发中",
        vehicleGPSTracking: "车辆GPS追踪",
        connected: "已连接",
        disconnected: "未连接",
        speed: "速度",
        Moving: "行驶中",
        Idling: "空转",
        Parking: "停车",
        offline: "离线",
        unknown: "未知",
        vehicleList: "车辆列表",
        all: "全部",
        motorcycle: "摩托车",
        car: "汽车",
        emailAddress: "电子邮箱",
        officeLocation: "办公地点",
        accountSettings: "账户设置",
        notifications: "通知",
        privacyAndSecurity: "隐私与安全",
        appPreferences: "应用偏好",
        support: "支持",
        contactSupport: "联系支持",
        helpCenter: "帮助中心",
        welcome: "欢迎",
        dashboard: "仪表盘",
        quickActions: "快捷操作",
        recentActivities: "最近活动",
        search: "搜索",
        noMoreData: "没有更多数据",
        noDataFound: "未找到数据",
        filter: "筛选",
        today: "今天",
        thisWeek: "本周",
        thisMonth: "本月",
        total: "总计",
        amount: "金额",
        status: "状态",
        date: "日期",
        name: "姓名",
        active: "启用",
        inactive: "停用",
        loading: "加载中...",
        editProfile: "编辑资料",
        username: "用户名",
        cancel: "取消",
        saveChanges: "保存更改",
        confirmLogout: "您确定要登出吗？",
        recommended: "推荐",
        notRecommended: "不推荐",
        holded: "保留",
        other: "其他",
        candidate: "候选人",
        hrd: "人权捍卫者",
        joined: "加入",
        employees: "员工",
        salaryOffers: "薪资报价",
        greeting_morning: "早上好",
        greeting_afternoon: "下午好",
        greeting_evening: "晚上好",
        greeting_night: "晚上好",
        welcomeMessage: "今日公司概览",
        allStatuses: "所有状态",
        fullName: "全名",
        normalizeDoors: "恢复门状态",
        allDepartments: "所有部门",
        employeeStatus: "员工状态",
        device: "设备",
        allDevices: "所有设备",
        category: "类别",
        allCategories: "所有类别",
        changePassword: "更改密码",
        currentPassword: "当前密码",
        newPassword: "新密码",
        confirmNewPassword: "确认新密码",
        credential: "用户名 / 邮箱",
        allMenus: "显示所有",
        accessDoors: "访问门",
        pageNotFound: "页面未找到",
        pageNotFoundDesc: "您要找的页面不存在或已被移动",
        backToHome: "返回主页",
        recruitments: "招聘",
        miscellaneous: "杂项",
        welcomeBack: "欢迎回来",
        forbidden: "禁止",
        forbiddenDesc: "您无权访问此页面",
        language: "语言",
        english: "英语",
        indonesian: "印尼语",
        chinese: "中文",
        theme: "主题",
        light: "浅色",
        dark: "深色",
        system: "系统",
        close: "关",
        menuList: "菜单列表",
    },
};

interface LanguageProviderProps {
    children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
    const [language, setLanguage] = useState<Language>("en");

    useEffect(() => {
        const savedLanguage = localStorage.getItem("language") as Language;
        if (savedLanguage && ["en", "id", "zh"].includes(savedLanguage)) {
            setLanguage(savedLanguage);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem("language", lang);
    };

    const t = (key: string): string => {
        return translations[language][key as keyof (typeof translations)[typeof language]] || key;
    };

    return <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>{children}</LanguageContext.Provider>;
};
