import 'package:flutter/material.dart';

class AppLocalizations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('id'),
    Locale('zh'),
  ];

  static const List<LocalizationsDelegate> localizationsDelegates = [
    // Add your localization delegates here
    // For now, we'll use a simple implementation
  ];

  static Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'email': 'E-Mail',
      'password': 'Password',
      'login': 'Login',
      'logout': 'Logout',
      'forgotPassword': 'Forgot Password?',
      'home': 'Home',
      'recruitment': 'Recruitment',
      'sales': 'Sales',
      'employee': 'Employee',
      'profile': 'Profile',
      'dashboard': 'Dashboard',
      'candidates': 'Candidates',
      'salaryOffers': 'Salary Offers',
      'dailyQuotes': 'Daily Quotes',
      'pointOfSales': 'Point of Sales',
      'salesIns': 'Sales Ins',
      'employees': 'Employees',
      'accessDoors': 'Access Doors',
      'gpsView': 'GPS View',
      'welcome': 'Welcome',
      'welcomeBack': 'Welcome Back',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'filter': 'Filter',
      'noDataFound': 'No data found',
      'tryAgain': 'Try Again',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'english': 'English',
      'indonesian': 'Indonesian',
      'chinese': 'Chinese',
    },
    'id': {
      'email': 'E-Mail',
      'password': 'Kata Sandi',
      'login': 'Masuk',
      'logout': 'Keluar',
      'forgotPassword': 'Lupa Kata Sandi?',
      'home': 'Beranda',
      'recruitment': 'Rekrutmen',
      'sales': 'Sales',
      'employee': 'Karyawan',
      'profile': 'Profil',
      'dashboard': 'Dasbor',
      'candidates': 'Kandidat',
      'salaryOffers': 'Penawaran Gaji',
      'dailyQuotes': 'Penawaran Harian',
      'pointOfSales': 'Titik Penjualan',
      'salesIns': 'Penjualan Masuk',
      'employees': 'Karyawan',
      'accessDoors': 'Akses Pintu',
      'gpsView': 'GPS Kendaraan',
      'welcome': 'Selamat Datang',
      'welcomeBack': 'Selamat Datang Kembali',
      'loading': 'Memuat...',
      'error': 'Kesalahan',
      'success': 'Berhasil',
      'cancel': 'Batal',
      'save': 'Simpan',
      'delete': 'Hapus',
      'edit': 'Edit',
      'add': 'Tambah',
      'search': 'Cari',
      'filter': 'Filter',
      'noDataFound': 'Data tidak ditemukan',
      'tryAgain': 'Coba Lagi',
      'settings': 'Pengaturan',
      'language': 'Bahasa',
      'theme': 'Tema',
      'light': 'Terang',
      'dark': 'Gelap',
      'system': 'Sistem',
      'english': 'Bahasa Inggris',
      'indonesian': 'Bahasa Indonesia',
      'chinese': 'Bahasa Mandarin',
    },
    'zh': {
      'email': '电子邮件',
      'password': '密码',
      'login': '登录',
      'logout': '登出',
      'forgotPassword': '忘记密码？',
      'home': '首页',
      'recruitment': '招聘',
      'sales': '销售',
      'employee': '员工',
      'profile': '个人资料',
      'dashboard': '仪表盘',
      'candidates': '候选人',
      'salaryOffers': '薪资提案',
      'dailyQuotes': '每日报价',
      'pointOfSales': '销售点',
      'salesIns': '销售入账',
      'employees': '员工',
      'accessDoors': '门禁',
      'gpsView': 'GPS视图',
      'welcome': '欢迎',
      'welcomeBack': '欢迎回来',
      'loading': '加载中...',
      'error': '错误',
      'success': '成功',
      'cancel': '取消',
      'save': '保存',
      'delete': '删除',
      'edit': '编辑',
      'add': '添加',
      'search': '搜索',
      'filter': '筛选',
      'noDataFound': '未找到数据',
      'tryAgain': '重试',
      'settings': '设置',
      'language': '语言',
      'theme': '主题',
      'light': '浅色',
      'dark': '深色',
      'system': '系统',
      'english': '英语',
      'indonesian': '印尼语',
      'chinese': '中文',
    },
  };

  static String translate(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}

extension AppLocalizationsExtension on BuildContext {
  String t(String key) {
    // Get current locale from provider or use default
    final languageCode = Localizations.of(this).languageCode;
    return AppLocalizations.translate(key, languageCode);
  }
}